add_test( [==[Vec2 arithmetic]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Vec2 arithmetic]==]  )
set_tests_properties( [==[Vec2 arithmetic]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Vec2 length and dot]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Vec2 length and dot]==]  )
set_tests_properties( [==[Vec2 length and dot]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Vec2 normalized]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Vec2 normalized]==]  )
set_tests_properties( [==[Vec2 normalized]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Vec2 rotation]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Vec2 rotation]==]  )
set_tests_properties( [==[Vec2 rotation]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( cross2d /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests cross2d  )
set_tests_properties( cross2d PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[RigidBody at rest stays at rest]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[RigidBody at rest stays at rest]==]  )
set_tests_properties( [==[RigidBody at rest stays at rest]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Constant force produces expected acceleration]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Constant force produces expected acceleration]==]  )
set_tests_properties( [==[Constant force produces expected acceleration]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Torque changes angular velocity]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Torque changes angular velocity]==]  )
set_tests_properties( [==[Torque changes angular velocity]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Linear drag reduces velocity]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Linear drag reduces velocity]==]  )
set_tests_properties( [==[Linear drag reduces velocity]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Angular drag reduces angular velocity]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Angular drag reduces angular velocity]==]  )
set_tests_properties( [==[Angular drag reduces angular velocity]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Rear thruster produces forward force]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Rear thruster produces forward force]==]  )
set_tests_properties( [==[Rear thruster produces forward force]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Thruster at zero power produces no force]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Thruster at zero power produces no force]==]  )
set_tests_properties( [==[Thruster at zero power produces no force]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Left-rear thruster produces torque]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Left-rear thruster produces torque]==]  )
set_tests_properties( [==[Left-rear thruster produces torque]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Thruster rotates with body]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Thruster rotates with body]==]  )
set_tests_properties( [==[Thruster rotates with body]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Equal opposite side thrusters cancel rotation]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Equal opposite side thrusters cancel rotation]==]  )
set_tests_properties( [==[Equal opposite side thrusters cancel rotation]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid with rear thruster moves forward]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid with rear thruster moves forward]==]  )
set_tests_properties( [==[Boid with rear thruster moves forward]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid with left-rear thruster rotates and curves]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid with left-rear thruster rotates and curves]==]  )
set_tests_properties( [==[Boid with left-rear thruster rotates and curves]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid with equal side thrusters goes straight]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid with equal side thrusters goes straight]==]  )
set_tests_properties( [==[Boid with equal side thrusters goes straight]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid with no thruster power stays put]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid with no thruster power stays put]==]  )
set_tests_properties( [==[Boid with no thruster power stays put]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Load simple_boid.json]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Load simple_boid.json]==]  )
set_tests_properties( [==[Load simple_boid.json]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Create boid from spec]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Create boid from spec]==]  )
set_tests_properties( [==[Create boid from spec]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Round-trip save and reload]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Round-trip save and reload]==]  )
set_tests_properties( [==[Round-trip save and reload]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Invalid file throws]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Invalid file throws]==]  )
set_tests_properties( [==[Invalid file throws]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Spec without genome loads with no genome]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Spec without genome loads with no genome]==]  )
set_tests_properties( [==[Spec without genome loads with no genome]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Genome round-trip: save and reload preserves genome]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Genome round-trip: save and reload preserves genome]==]  )
set_tests_properties( [==[Genome round-trip: save and reload preserves genome]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Genome round-trip: network produces identical outputs]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Genome round-trip: network produces identical outputs]==]  )
set_tests_properties( [==[Genome round-trip: network produces identical outputs]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Spec to boid integration: fire rear thruster and move]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Spec to boid integration: fire rear thruster and move]==]  )
set_tests_properties( [==[Spec to boid integration: fire rear thruster and move]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[World steps boid physics]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[World steps boid physics]==]  )
set_tests_properties( [==[World steps boid physics]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Toroidal wrapping X axis]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Toroidal wrapping X axis]==]  )
set_tests_properties( [==[Toroidal wrapping X axis]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Toroidal wrapping Y axis]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Toroidal wrapping Y axis]==]  )
set_tests_properties( [==[Toroidal wrapping Y axis]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Multiple boids update independently]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Multiple boids update independently]==]  )
set_tests_properties( [==[Multiple boids update independently]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Toroidal delta within half-world is raw difference]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Toroidal delta within half-world is raw difference]==]  )
set_tests_properties( [==[Toroidal delta within half-world is raw difference]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Toroidal delta wraps across X boundary]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Toroidal delta wraps across X boundary]==]  )
set_tests_properties( [==[Toroidal delta wraps across X boundary]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Toroidal delta wraps across Y boundary]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Toroidal delta wraps across Y boundary]==]  )
set_tests_properties( [==[Toroidal delta wraps across Y boundary]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Toroidal delta wraps across both axes (corner)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Toroidal delta wraps across both axes (corner)]==]  )
set_tests_properties( [==[Toroidal delta wraps across both axes (corner)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[toroidal_distance_sq matches delta length_squared]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[toroidal_distance_sq matches delta length_squared]==]  )
set_tests_properties( [==[toroidal_distance_sq matches delta length_squared]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Grid insert and query finds nearby boid]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Grid insert and query finds nearby boid]==]  )
set_tests_properties( [==[Grid insert and query finds nearby boid]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Grid query near X edge finds wrapped boids (toroidal)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Grid query near X edge finds wrapped boids (toroidal)]==]  )
set_tests_properties( [==[Grid query near X edge finds wrapped boids (toroidal)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Grid query near Y edge finds wrapped boids (toroidal)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Grid query near Y edge finds wrapped boids (toroidal)]==]  )
set_tests_properties( [==[Grid query near Y edge finds wrapped boids (toroidal)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Grid query at corner finds boids across both axis wraps]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Grid query at corner finds boids across both axis wraps]==]  )
set_tests_properties( [==[Grid query at corner finds boids across both axis wraps]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Grid clear removes all entries]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Grid clear removes all entries]==]  )
set_tests_properties( [==[Grid clear removes all entries]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Non-toroidal grid does not wrap at edges]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Non-toroidal grid does not wrap at edges]==]  )
set_tests_properties( [==[Non-toroidal grid does not wrap at edges]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Grid query with small radius has no false negatives]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Grid query with small radius has no false negatives]==]  )
set_tests_properties( [==[Grid query with small radius has no false negatives]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[World grid matches brute-force neighbour check]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[World grid matches brute-force neighbour check]==]  )
set_tests_properties( [==[World grid matches brute-force neighbour check]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[World grid is consistent after multiple steps]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[World grid is consistent after multiple steps]==]  )
set_tests_properties( [==[World grid is consistent after multiple steps]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[angle_in_arc: center hit]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[angle_in_arc: center hit]==]  )
set_tests_properties( [==[angle_in_arc: center hit]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[angle_in_arc: edge of arc]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[angle_in_arc: edge of arc]==]  )
set_tests_properties( [==[angle_in_arc: edge of arc]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[angle_in_arc: outside arc]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[angle_in_arc: outside arc]==]  )
set_tests_properties( [==[angle_in_arc: outside arc]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[angle_in_arc: wrapping around ±π]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[angle_in_arc: wrapping around ±π]==]  )
set_tests_properties( [==[angle_in_arc: wrapping around ±π]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Single boid directly ahead detected]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Single boid directly ahead detected]==]  )
set_tests_properties( [==[Single boid directly ahead detected]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid outside arc not detected]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid outside arc not detected]==]  )
set_tests_properties( [==[Boid outside arc not detected]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid outside range not detected]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid outside range not detected]==]  )
set_tests_properties( [==[Boid outside range not detected]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Self not detected]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Self not detected]==]  )
set_tests_properties( [==[Self not detected]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Toroidal wrap: boid across world edge detected]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Toroidal wrap: boid across world edge detected]==]  )
set_tests_properties( [==[Toroidal wrap: boid across world edge detected]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[EntityFilter: prey sensor ignores predators]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[EntityFilter: prey sensor ignores predators]==]  )
set_tests_properties( [==[EntityFilter: prey sensor ignores predators]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Rotated boid: sensor arc moves with heading]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Rotated boid: sensor arc moves with heading]==]  )
set_tests_properties( [==[Rotated boid: sensor arc moves with heading]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[SectorDensity signal type]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[SectorDensity signal type]==]  )
set_tests_properties( [==[SectorDensity signal type]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Multiple sensors produce independent outputs]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Multiple sensors produce independent outputs]==]  )
set_tests_properties( [==[Multiple sensors produce independent outputs]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[World runs sensors each tick]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[World runs sensors each tick]==]  )
set_tests_properties( [==[World runs sensors each tick]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food sensor detects food within arc and range]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food sensor detects food within arc and range]==]  )
set_tests_properties( [==[Food sensor detects food within arc and range]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food sensor ignores boids]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food sensor ignores boids]==]  )
set_tests_properties( [==[Food sensor ignores boids]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid sensor ignores food]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid sensor ignores food]==]  )
set_tests_properties( [==[Boid sensor ignores food]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food sensor: food outside arc not detected]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food sensor: food outside arc not detected]==]  )
set_tests_properties( [==[Food sensor: food outside arc not detected]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food sensor: food outside range not detected]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food sensor: food outside range not detected]==]  )
set_tests_properties( [==[Food sensor: food outside range not detected]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food sensor: toroidal food detection across world edge]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food sensor: toroidal food detection across world edge]==]  )
set_tests_properties( [==[Food sensor: toroidal food detection across world edge]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[World runs food sensors via step()]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[World runs food sensors via step()]==]  )
set_tests_properties( [==[World runs food sensors via step()]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: all-zero weights produce sigmoid(0) outputs]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: all-zero weights produce sigmoid(0) outputs]==]  )
set_tests_properties( [==[DirectWire: all-zero weights produce sigmoid(0) outputs]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: single weight drives one output]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: single weight drives one output]==]  )
set_tests_properties( [==[DirectWire: single weight drives one output]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: large positive weight saturates toward 1]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: large positive weight saturates toward 1]==]  )
set_tests_properties( [==[DirectWire: large positive weight saturates toward 1]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: large negative weight saturates toward 0]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: large negative weight saturates toward 0]==]  )
set_tests_properties( [==[DirectWire: large negative weight saturates toward 0]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: bias shifts output]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: bias shifts output]==]  )
set_tests_properties( [==[DirectWire: bias shifts output]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: multiple inputs sum correctly]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: multiple inputs sum correctly]==]  )
set_tests_properties( [==[DirectWire: multiple inputs sum correctly]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: more sensors than thrusters (extra inputs ignored)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: more sensors than thrusters (extra inputs ignored)]==]  )
set_tests_properties( [==[DirectWire: more sensors than thrusters (extra inputs ignored)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: fewer sensors than thrusters (extra outputs zeroed)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: fewer sensors than thrusters (extra outputs zeroed)]==]  )
set_tests_properties( [==[DirectWire: fewer sensors than thrusters (extra outputs zeroed)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: all-one inputs with identity-like weights]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: all-one inputs with identity-like weights]==]  )
set_tests_properties( [==[DirectWire: all-one inputs with identity-like weights]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[DirectWire: polymorphic use through ProcessingNetwork pointer]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[DirectWire: polymorphic use through ProcessingNetwork pointer]==]  )
set_tests_properties( [==[DirectWire: polymorphic use through ProcessingNetwork pointer]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: correct node count and types]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: correct node count and types]==]  )
set_tests_properties( [==[Minimal genome: correct node count and types]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: fully connected input→output]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: fully connected input→output]==]  )
set_tests_properties( [==[Minimal genome: fully connected input→output]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: unique innovation numbers]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: unique innovation numbers]==]  )
set_tests_properties( [==[Minimal genome: unique innovation numbers]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: connections link inputs to outputs only]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: connections link inputs to outputs only]==]  )
set_tests_properties( [==[Minimal genome: connections link inputs to outputs only]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: node ids are sequential]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: node ids are sequential]==]  )
set_tests_properties( [==[Minimal genome: node ids are sequential]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: input nodes have Linear activation]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: input nodes have Linear activation]==]  )
set_tests_properties( [==[Minimal genome: input nodes have Linear activation]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: output nodes have Sigmoid activation]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: output nodes have Sigmoid activation]==]  )
set_tests_properties( [==[Minimal genome: output nodes have Sigmoid activation]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: all weights start at zero]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: all weights start at zero]==]  )
set_tests_properties( [==[Minimal genome: all weights start at zero]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Minimal genome: innovation counter is consumed correctly]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Minimal genome: innovation counter is consumed correctly]==]  )
set_tests_properties( [==[Minimal genome: innovation counter is consumed correctly]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: minimal genome, zero weights → sigmoid(0) outputs]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: minimal genome\, zero weights → sigmoid(0) outputs]==]  )
set_tests_properties( [==[NeatNetwork: minimal genome, zero weights → sigmoid(0) outputs]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: single large positive weight → output near 1]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: single large positive weight → output near 1]==]  )
set_tests_properties( [==[NeatNetwork: single large positive weight → output near 1]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: single large negative weight → output near 0]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: single large negative weight → output near 0]==]  )
set_tests_properties( [==[NeatNetwork: single large negative weight → output near 0]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: matches DirectWireNetwork for minimal genome]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: matches DirectWireNetwork for minimal genome]==]  )
set_tests_properties( [==[NeatNetwork: matches DirectWireNetwork for minimal genome]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: disabled connection is ignored]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: disabled connection is ignored]==]  )
set_tests_properties( [==[NeatNetwork: disabled connection is ignored]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: output node bias works]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: output node bias works]==]  )
set_tests_properties( [==[NeatNetwork: output node bias works]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: one hidden node (input → hidden → output)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: one hidden node (input → hidden → output)]==]  )
set_tests_properties( [==[NeatNetwork: one hidden node (input → hidden → output)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: two hidden nodes in chain]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: two hidden nodes in chain]==]  )
set_tests_properties( [==[NeatNetwork: two hidden nodes in chain]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: diamond topology (two paths to output)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: diamond topology (two paths to output)]==]  )
set_tests_properties( [==[NeatNetwork: diamond topology (two paths to output)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: reset clears node values]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: reset clears node values]==]  )
set_tests_properties( [==[NeatNetwork: reset clears node values]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[NeatNetwork: polymorphic use via ProcessingNetwork]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[NeatNetwork: polymorphic use via ProcessingNetwork]==]  )
set_tests_properties( [==[NeatNetwork: polymorphic use via ProcessingNetwork]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Brain-driven boid: minimal genome gives sigmoid(0) thruster power]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Brain-driven boid: minimal genome gives sigmoid(0) thruster power]==]  )
set_tests_properties( [==[Brain-driven boid: minimal genome gives sigmoid(0) thruster power]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Brain-driven boid: world step activates brain]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Brain-driven boid: world step activates brain]==]  )
set_tests_properties( [==[Brain-driven boid: world step activates brain]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Boid without brain: thrusters unchanged by world step]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Boid without brain: thrusters unchanged by world step]==]  )
set_tests_properties( [==[Boid without brain: thrusters unchanged by world step]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Brain responds to sensor input: boid ahead drives thruster output]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Brain responds to sensor input: boid ahead drives thruster output]==]  )
set_tests_properties( [==[Brain responds to sensor input: boid ahead drives thruster output]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Full pipeline: brain-driven boid accelerates forward]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Full pipeline: brain-driven boid accelerates forward]==]  )
set_tests_properties( [==[Full pipeline: brain-driven boid accelerates forward]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Brain-driven boid: spec with genome creates brain automatically]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Brain-driven boid: spec with genome creates brain automatically]==]  )
set_tests_properties( [==[Brain-driven boid: spec with genome creates brain automatically]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[InnovationTracker: same pair returns same number]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[InnovationTracker: same pair returns same number]==]  )
set_tests_properties( [==[InnovationTracker: same pair returns same number]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[InnovationTracker: different pairs get different numbers]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[InnovationTracker: different pairs get different numbers]==]  )
set_tests_properties( [==[InnovationTracker: different pairs get different numbers]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[InnovationTracker: direction matters]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[InnovationTracker: direction matters]==]  )
set_tests_properties( [==[InnovationTracker: direction matters]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[InnovationTracker: sequential numbering]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[InnovationTracker: sequential numbering]==]  )
set_tests_properties( [==[InnovationTracker: sequential numbering]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[InnovationTracker: new_generation resets cache]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[InnovationTracker: new_generation resets cache]==]  )
set_tests_properties( [==[InnovationTracker: new_generation resets cache]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[InnovationTracker: next_innovation reflects state]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[InnovationTracker: next_innovation reflects state]==]  )
set_tests_properties( [==[InnovationTracker: next_innovation reflects state]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_weights: weights change]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_weights: weights change]==]  )
set_tests_properties( [==[mutate_weights: weights change]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_weights: with zero probabilities, weights unchanged]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_weights: with zero probabilities\, weights unchanged]==]  )
set_tests_properties( [==[mutate_weights: with zero probabilities, weights unchanged]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_connection: adds a new connection]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_connection: adds a new connection]==]  )
set_tests_properties( [==[mutate_add_connection: adds a new connection]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_connection: fully connected returns false]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_connection: fully connected returns false]==]  )
set_tests_properties( [==[mutate_add_connection: fully connected returns false]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_connection: no duplicate connections]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_connection: no duplicate connections]==]  )
set_tests_properties( [==[mutate_add_connection: no duplicate connections]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_connection: doesn't connect to input nodes]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_connection: doesn't connect to input nodes]==]  )
set_tests_properties( [==[mutate_add_connection: doesn't connect to input nodes]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_node: splits a connection]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_node: splits a connection]==]  )
set_tests_properties( [==[mutate_add_node: splits a connection]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_node: original connection is disabled]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_node: original connection is disabled]==]  )
set_tests_properties( [==[mutate_add_node: original connection is disabled]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_node: preserves behaviour (weight 1.0 in, original out)]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_node: preserves behaviour (weight 1.0 in\, original out)]==]  )
set_tests_properties( [==[mutate_add_node: preserves behaviour (weight 1.0 in, original out)]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_add_node: no enabled connections returns false]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_add_node: no enabled connections returns false]==]  )
set_tests_properties( [==[mutate_add_node: no enabled connections returns false]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_toggle_connection: flips enabled state]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_toggle_connection: flips enabled state]==]  )
set_tests_properties( [==[mutate_toggle_connection: flips enabled state]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_delete_connection: removes a connection]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_delete_connection: removes a connection]==]  )
set_tests_properties( [==[mutate_delete_connection: removes a connection]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_delete_connection: orphaned hidden node is removed]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_delete_connection: orphaned hidden node is removed]==]  )
set_tests_properties( [==[mutate_delete_connection: orphaned hidden node is removed]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[mutate_delete_connection: empty genome returns false]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[mutate_delete_connection: empty genome returns false]==]  )
set_tests_properties( [==[mutate_delete_connection: empty genome returns false]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Mutated genome builds a valid NeatNetwork]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Mutated genome builds a valid NeatNetwork]==]  )
set_tests_properties( [==[Mutated genome builds a valid NeatNetwork]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Many mutations produce diverse genomes]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Many mutations produce diverse genomes]==]  )
set_tests_properties( [==[Many mutations produce diverse genomes]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: identical parents produce identical offspring]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: identical parents produce identical offspring]==]  )
set_tests_properties( [==[Crossover: identical parents produce identical offspring]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: fitter parent's excess genes inherited]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: fitter parent's excess genes inherited]==]  )
set_tests_properties( [==[Crossover: fitter parent's excess genes inherited]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: other parent's excess genes NOT inherited]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: other parent's excess genes NOT inherited]==]  )
set_tests_properties( [==[Crossover: other parent's excess genes NOT inherited]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: matching genes from roughly 50/50 parents]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: matching genes from roughly 50/50 parents]==]  )
set_tests_properties( [==[Crossover: matching genes from roughly 50/50 parents]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: disabled gene handling]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: disabled gene handling]==]  )
set_tests_properties( [==[Crossover: disabled gene handling]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: different hidden nodes produce valid offspring]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: different hidden nodes produce valid offspring]==]  )
set_tests_properties( [==[Crossover: different hidden nodes produce valid offspring]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: offspring builds a valid NeatNetwork]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: offspring builds a valid NeatNetwork]==]  )
set_tests_properties( [==[Crossover: offspring builds a valid NeatNetwork]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Crossover: nodes sorted by id]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Crossover: nodes sorted by id]==]  )
set_tests_properties( [==[Crossover: nodes sorted by id]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Compatibility: identical genomes have distance 0]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Compatibility: identical genomes have distance 0]==]  )
set_tests_properties( [==[Compatibility: identical genomes have distance 0]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Compatibility: weight difference only]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Compatibility: weight difference only]==]  )
set_tests_properties( [==[Compatibility: weight difference only]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Compatibility: excess genes increase distance]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Compatibility: excess genes increase distance]==]  )
set_tests_properties( [==[Compatibility: excess genes increase distance]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Compatibility: disjoint genes increase distance]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Compatibility: disjoint genes increase distance]==]  )
set_tests_properties( [==[Compatibility: disjoint genes increase distance]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Compatibility: empty genomes have distance 0]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Compatibility: empty genomes have distance 0]==]  )
set_tests_properties( [==[Compatibility: empty genomes have distance 0]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[assign_species: all identical go to one species]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[assign_species: all identical go to one species]==]  )
set_tests_properties( [==[assign_species: all identical go to one species]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[assign_species: divergent genomes create multiple species]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[assign_species: divergent genomes create multiple species]==]  )
set_tests_properties( [==[assign_species: divergent genomes create multiple species]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[assign_species: empty species are removed]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[assign_species: empty species are removed]==]  )
set_tests_properties( [==[assign_species: empty species are removed]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Population: initial size matches params]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Population: initial size matches params]==]  )
set_tests_properties( [==[Population: initial size matches params]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Population: all in one species initially]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Population: all in one species initially]==]  )
set_tests_properties( [==[Population: all in one species initially]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Population: evaluate sets fitness values]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Population: evaluate sets fitness values]==]  )
set_tests_properties( [==[Population: evaluate sets fitness values]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Population: advance preserves population size]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Population: advance preserves population size]==]  )
set_tests_properties( [==[Population: advance preserves population size]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Population: multiple generations produce diversity]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Population: multiple generations produce diversity]==]  )
set_tests_properties( [==[Population: multiple generations produce diversity]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Population: elitism preserves best genome]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Population: elitism preserves best genome]==]  )
set_tests_properties( [==[Population: elitism preserves best genome]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Population: all genomes build valid networks]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Population: all genomes build valid networks]==]  )
set_tests_properties( [==[Population: all genomes build valid networks]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[XOR benchmark: NEAT solves XOR]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[XOR benchmark: NEAT solves XOR]==]  )
set_tests_properties( [==[XOR benchmark: NEAT solves XOR]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food: boid eats food within radius]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food: boid eats food within radius]==]  )
set_tests_properties( [==[Food: boid eats food within radius]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food: boid does not eat food outside radius]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food: boid does not eat food outside radius]==]  )
set_tests_properties( [==[Food: boid does not eat food outside radius]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food: toroidal eating across boundary]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food: toroidal eating across boundary]==]  )
set_tests_properties( [==[Food: toroidal eating across boundary]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food: food respawns up to max]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food: food respawns up to max]==]  )
set_tests_properties( [==[Food: food respawns up to max]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food: no spawning without rng]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food: no spawning without rng]==]  )
set_tests_properties( [==[Food: no spawning without rng]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Energy: metabolism drains energy over time]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Energy: metabolism drains energy over time]==]  )
set_tests_properties( [==[Energy: metabolism drains energy over time]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Energy: thrust costs energy]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Energy: thrust costs energy]==]  )
set_tests_properties( [==[Energy: thrust costs energy]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Energy: boid dies at zero energy]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Energy: boid dies at zero energy]==]  )
set_tests_properties( [==[Energy: boid dies at zero energy]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Energy: dead boid does not move]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Energy: dead boid does not move]==]  )
set_tests_properties( [==[Energy: dead boid does not move]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Energy: dead boid does not eat food]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Energy: dead boid does not eat food]==]  )
set_tests_properties( [==[Energy: dead boid does not eat food]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Fitness: total_energy_gained tracks cumulative food eaten]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Fitness: total_energy_gained tracks cumulative food eaten]==]  )
set_tests_properties( [==[Fitness: total_energy_gained tracks cumulative food eaten]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Food: boid with high thrust runs out faster]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Food: boid with high thrust runs out faster]==]  )
set_tests_properties( [==[Food: boid with high thrust runs out faster]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Evolution: evaluation harness produces non-zero fitness]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Evolution: evaluation harness produces non-zero fitness]==]  )
set_tests_properties( [==[Evolution: evaluation harness produces non-zero fitness]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Evolution: moving boids outperform stationary ones]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Evolution: moving boids outperform stationary ones]==]  )
set_tests_properties( [==[Evolution: moving boids outperform stationary ones]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Evolution: fitness improves over generations]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Evolution: fitness improves over generations]==]  )
set_tests_properties( [==[Evolution: fitness improves over generations]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Evolution: all evolved genomes produce valid networks]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Evolution: all evolved genomes produce valid networks]==]  )
set_tests_properties( [==[Evolution: all evolved genomes produce valid networks]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Headless: completes N generations without crash]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Headless: completes N generations without crash]==]  )
set_tests_properties( [==[Headless: completes N generations without crash]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Headless: saved champion genome loads and produces valid network]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Headless: saved champion genome loads and produces valid network]==]  )
set_tests_properties( [==[Headless: saved champion genome loads and produces valid network]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Headless: champion genome replays in world without crash]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Headless: champion genome replays in world without crash]==]  )
set_tests_properties( [==[Headless: champion genome replays in world without crash]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Load sim_config.json]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Load sim_config.json]==]  )
set_tests_properties( [==[Load sim_config.json]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Sim config uses WorldConfig defaults for missing fields]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Sim config uses WorldConfig defaults for missing fields]==]  )
set_tests_properties( [==[Sim config uses WorldConfig defaults for missing fields]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Sim config throws on missing file]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Sim config throws on missing file]==]  )
set_tests_properties( [==[Sim config throws on missing file]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Sim config: uniform food mode parsed]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Sim config: uniform food mode parsed]==]  )
set_tests_properties( [==[Sim config: uniform food mode parsed]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Sim config: patch food mode parsed]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Sim config: patch food mode parsed]==]  )
set_tests_properties( [==[Sim config: patch food mode parsed]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[Sim config: missing mode defaults to uniform]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[Sim config: missing mode defaults to uniform]==]  )
set_tests_properties( [==[Sim config: missing mode defaults to uniform]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[UniformFoodSource: pre_seed spawns half of max]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[UniformFoodSource: pre_seed spawns half of max]==]  )
set_tests_properties( [==[UniformFoodSource: pre_seed spawns half of max]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[UniformFoodSource: spawn respects max]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[UniformFoodSource: spawn respects max]==]  )
set_tests_properties( [==[UniformFoodSource: spawn respects max]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[PatchFoodSource: pre_seed spawns correct count]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[PatchFoodSource: pre_seed spawns correct count]==]  )
set_tests_properties( [==[PatchFoodSource: pre_seed spawns correct count]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[PatchFoodSource: food is clustered]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[PatchFoodSource: food is clustered]==]  )
set_tests_properties( [==[PatchFoodSource: food is clustered]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[PatchFoodSource: new patch spawns when one is depleted]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[PatchFoodSource: new patch spawns when one is depleted]==]  )
set_tests_properties( [==[PatchFoodSource: new patch spawns when one is depleted]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[PatchFoodSource: does not over-spawn]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[PatchFoodSource: does not over-spawn]==]  )
set_tests_properties( [==[PatchFoodSource: does not over-spawn]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[PatchFoodSource: partial depletion does not trigger new patch]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[PatchFoodSource: partial depletion does not trigger new patch]==]  )
set_tests_properties( [==[PatchFoodSource: partial depletion does not trigger new patch]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[World with patch food source: food stays near target]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[World with patch food source: food stays near target]==]  )
set_tests_properties( [==[World with patch food source: food stays near target]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
add_test( [==[World backward compat: flat config fields still work]==] /Users/danolner/Code/claude/wildboids/build-release/wildboids_tests [==[World backward compat: flat config fields still work]==]  )
set_tests_properties( [==[World backward compat: flat config fields still work]==] PROPERTIES WORKING_DIRECTORY /Users/danolner/Code/claude/wildboids/build-release)
set( wildboids_tests_TESTS [==[Vec2 arithmetic]==] [==[Vec2 length and dot]==] [==[Vec2 normalized]==] [==[Vec2 rotation]==] cross2d [==[RigidBody at rest stays at rest]==] [==[Constant force produces expected acceleration]==] [==[Torque changes angular velocity]==] [==[Linear drag reduces velocity]==] [==[Angular drag reduces angular velocity]==] [==[Rear thruster produces forward force]==] [==[Thruster at zero power produces no force]==] [==[Left-rear thruster produces torque]==] [==[Thruster rotates with body]==] [==[Equal opposite side thrusters cancel rotation]==] [==[Boid with rear thruster moves forward]==] [==[Boid with left-rear thruster rotates and curves]==] [==[Boid with equal side thrusters goes straight]==] [==[Boid with no thruster power stays put]==] [==[Load simple_boid.json]==] [==[Create boid from spec]==] [==[Round-trip save and reload]==] [==[Invalid file throws]==] [==[Spec without genome loads with no genome]==] [==[Genome round-trip: save and reload preserves genome]==] [==[Genome round-trip: network produces identical outputs]==] [==[Spec to boid integration: fire rear thruster and move]==] [==[World steps boid physics]==] [==[Toroidal wrapping X axis]==] [==[Toroidal wrapping Y axis]==] [==[Multiple boids update independently]==] [==[Toroidal delta within half-world is raw difference]==] [==[Toroidal delta wraps across X boundary]==] [==[Toroidal delta wraps across Y boundary]==] [==[Toroidal delta wraps across both axes (corner)]==] [==[toroidal_distance_sq matches delta length_squared]==] [==[Grid insert and query finds nearby boid]==] [==[Grid query near X edge finds wrapped boids (toroidal)]==] [==[Grid query near Y edge finds wrapped boids (toroidal)]==] [==[Grid query at corner finds boids across both axis wraps]==] [==[Grid clear removes all entries]==] [==[Non-toroidal grid does not wrap at edges]==] [==[Grid query with small radius has no false negatives]==] [==[World grid matches brute-force neighbour check]==] [==[World grid is consistent after multiple steps]==] [==[angle_in_arc: center hit]==] [==[angle_in_arc: edge of arc]==] [==[angle_in_arc: outside arc]==] [==[angle_in_arc: wrapping around ±π]==] [==[Single boid directly ahead detected]==] [==[Boid outside arc not detected]==] [==[Boid outside range not detected]==] [==[Self not detected]==] [==[Toroidal wrap: boid across world edge detected]==] [==[EntityFilter: prey sensor ignores predators]==] [==[Rotated boid: sensor arc moves with heading]==] [==[SectorDensity signal type]==] [==[Multiple sensors produce independent outputs]==] [==[World runs sensors each tick]==] [==[Food sensor detects food within arc and range]==] [==[Food sensor ignores boids]==] [==[Boid sensor ignores food]==] [==[Food sensor: food outside arc not detected]==] [==[Food sensor: food outside range not detected]==] [==[Food sensor: toroidal food detection across world edge]==] [==[World runs food sensors via step()]==] [==[DirectWire: all-zero weights produce sigmoid(0) outputs]==] [==[DirectWire: single weight drives one output]==] [==[DirectWire: large positive weight saturates toward 1]==] [==[DirectWire: large negative weight saturates toward 0]==] [==[DirectWire: bias shifts output]==] [==[DirectWire: multiple inputs sum correctly]==] [==[DirectWire: more sensors than thrusters (extra inputs ignored)]==] [==[DirectWire: fewer sensors than thrusters (extra outputs zeroed)]==] [==[DirectWire: all-one inputs with identity-like weights]==] [==[DirectWire: polymorphic use through ProcessingNetwork pointer]==] [==[Minimal genome: correct node count and types]==] [==[Minimal genome: fully connected input→output]==] [==[Minimal genome: unique innovation numbers]==] [==[Minimal genome: connections link inputs to outputs only]==] [==[Minimal genome: node ids are sequential]==] [==[Minimal genome: input nodes have Linear activation]==] [==[Minimal genome: output nodes have Sigmoid activation]==] [==[Minimal genome: all weights start at zero]==] [==[Minimal genome: innovation counter is consumed correctly]==] [==[NeatNetwork: minimal genome, zero weights → sigmoid(0) outputs]==] [==[NeatNetwork: single large positive weight → output near 1]==] [==[NeatNetwork: single large negative weight → output near 0]==] [==[NeatNetwork: matches DirectWireNetwork for minimal genome]==] [==[NeatNetwork: disabled connection is ignored]==] [==[NeatNetwork: output node bias works]==] [==[NeatNetwork: one hidden node (input → hidden → output)]==] [==[NeatNetwork: two hidden nodes in chain]==] [==[NeatNetwork: diamond topology (two paths to output)]==] [==[NeatNetwork: reset clears node values]==] [==[NeatNetwork: polymorphic use via ProcessingNetwork]==] [==[Brain-driven boid: minimal genome gives sigmoid(0) thruster power]==] [==[Brain-driven boid: world step activates brain]==] [==[Boid without brain: thrusters unchanged by world step]==] [==[Brain responds to sensor input: boid ahead drives thruster output]==] [==[Full pipeline: brain-driven boid accelerates forward]==] [==[Brain-driven boid: spec with genome creates brain automatically]==] [==[InnovationTracker: same pair returns same number]==] [==[InnovationTracker: different pairs get different numbers]==] [==[InnovationTracker: direction matters]==] [==[InnovationTracker: sequential numbering]==] [==[InnovationTracker: new_generation resets cache]==] [==[InnovationTracker: next_innovation reflects state]==] [==[mutate_weights: weights change]==] [==[mutate_weights: with zero probabilities, weights unchanged]==] [==[mutate_add_connection: adds a new connection]==] [==[mutate_add_connection: fully connected returns false]==] [==[mutate_add_connection: no duplicate connections]==] [==[mutate_add_connection: doesn't connect to input nodes]==] [==[mutate_add_node: splits a connection]==] [==[mutate_add_node: original connection is disabled]==] [==[mutate_add_node: preserves behaviour (weight 1.0 in, original out)]==] [==[mutate_add_node: no enabled connections returns false]==] [==[mutate_toggle_connection: flips enabled state]==] [==[mutate_delete_connection: removes a connection]==] [==[mutate_delete_connection: orphaned hidden node is removed]==] [==[mutate_delete_connection: empty genome returns false]==] [==[Mutated genome builds a valid NeatNetwork]==] [==[Many mutations produce diverse genomes]==] [==[Crossover: identical parents produce identical offspring]==] [==[Crossover: fitter parent's excess genes inherited]==] [==[Crossover: other parent's excess genes NOT inherited]==] [==[Crossover: matching genes from roughly 50/50 parents]==] [==[Crossover: disabled gene handling]==] [==[Crossover: different hidden nodes produce valid offspring]==] [==[Crossover: offspring builds a valid NeatNetwork]==] [==[Crossover: nodes sorted by id]==] [==[Compatibility: identical genomes have distance 0]==] [==[Compatibility: weight difference only]==] [==[Compatibility: excess genes increase distance]==] [==[Compatibility: disjoint genes increase distance]==] [==[Compatibility: empty genomes have distance 0]==] [==[assign_species: all identical go to one species]==] [==[assign_species: divergent genomes create multiple species]==] [==[assign_species: empty species are removed]==] [==[Population: initial size matches params]==] [==[Population: all in one species initially]==] [==[Population: evaluate sets fitness values]==] [==[Population: advance preserves population size]==] [==[Population: multiple generations produce diversity]==] [==[Population: elitism preserves best genome]==] [==[Population: all genomes build valid networks]==] [==[XOR benchmark: NEAT solves XOR]==] [==[Food: boid eats food within radius]==] [==[Food: boid does not eat food outside radius]==] [==[Food: toroidal eating across boundary]==] [==[Food: food respawns up to max]==] [==[Food: no spawning without rng]==] [==[Energy: metabolism drains energy over time]==] [==[Energy: thrust costs energy]==] [==[Energy: boid dies at zero energy]==] [==[Energy: dead boid does not move]==] [==[Energy: dead boid does not eat food]==] [==[Fitness: total_energy_gained tracks cumulative food eaten]==] [==[Food: boid with high thrust runs out faster]==] [==[Evolution: evaluation harness produces non-zero fitness]==] [==[Evolution: moving boids outperform stationary ones]==] [==[Evolution: fitness improves over generations]==] [==[Evolution: all evolved genomes produce valid networks]==] [==[Headless: completes N generations without crash]==] [==[Headless: saved champion genome loads and produces valid network]==] [==[Headless: champion genome replays in world without crash]==] [==[Load sim_config.json]==] [==[Sim config uses WorldConfig defaults for missing fields]==] [==[Sim config throws on missing file]==] [==[Sim config: uniform food mode parsed]==] [==[Sim config: patch food mode parsed]==] [==[Sim config: missing mode defaults to uniform]==] [==[UniformFoodSource: pre_seed spawns half of max]==] [==[UniformFoodSource: spawn respects max]==] [==[PatchFoodSource: pre_seed spawns correct count]==] [==[PatchFoodSource: food is clustered]==] [==[PatchFoodSource: new patch spawns when one is depleted]==] [==[PatchFoodSource: does not over-spawn]==] [==[PatchFoodSource: partial depletion does not trigger new patch]==] [==[World with patch food source: food stays near target]==] [==[World backward compat: flat config fields still work]==])
