if(EXISTS "/Users/danolner/Code/claude/wildboids/build-release/wildboids_tests-b12d07c_tests.cmake")
  include("/Users/danolner/Code/claude/wildboids/build-release/wildboids_tests-b12d07c_tests.cmake")
else()
  add_test(wildboids_tests_NOT_BUILT-b12d07c wildboids_tests_NOT_BUILT-b12d07c)
endif()
