/*
 * BoidsStartUp.java
 *
 * Created on 23 May 2007, 22:37
 */

package boids;

import java.util.Random;

/**
 *
 * @author  Olner Dan
 */
public class BoidsStartUp extends javax.swing.JFrame {
    
    //set random seed
    public static Random r = new Random(0);
    
    /** Creates new form BoidsStartUp */
    public BoidsStartUp() {
        initComponents();
        //size of boid cage...
        CAGE_XY = new int[2];
        CAGE_XY[0]=1000;
        CAGE_XY[1]=1000;
                
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boidsNoTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFieldOfView = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PreyDeathLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PredatorDeathLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTurningSpeed = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        foV1rad = new javax.swing.JTextField();
        foV2rad = new javax.swing.JTextField();
        foV3rad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("clear");

        jLabel1.setText("Number of boids:");

        boidsNoTxtField.setText("0");
        boidsNoTxtField.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                boidsNoTxtFieldMouseWheelMoved(evt);
            }
        });

        jLabel2.setText("Display field of view rule");

        jLabel3.setText("0 for none, 1 to 3 = 'how I see preyboids'");

        jLabel4.setText(" 4 to 6 = 'how I see predatorboids'");

        jFieldOfView.setText("0");
        jFieldOfView.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jFieldOfViewMouseWheelMoved(evt);
            }
        });
        jFieldOfView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldOfViewActionPerformed(evt);
            }
        });

        jLabel5.setText("Use mousewheel to change");

        jLabel6.setText("Number of prey deaths:");

        PreyDeathLabel.setFont(new java.awt.Font("Tahoma", 1, 10));

        jLabel7.setText("Number of predator deaths:");

        PredatorDeathLabel.setFont(new java.awt.Font("Tahoma", 1, 10));

        jLabel8.setText("Display speed (0 is fastest)");

        jTextField1.setText("2");
        jTextField1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTextField1MouseWheelMoved(evt);
            }
        });

        jLabel9.setText("Turning speed (fractions, e.g. 6 = 1/6)");

        jTurningSpeed.setText("6");
        jTurningSpeed.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTurningSpeedMouseWheelMoved(evt);
            }
        });

        jSlider1.setMaximum(300);
        jSlider1.setValue(100);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jSlider1AncestorRemoved(evt);
            }
        });

        jSlider2.setMaximum(300);
        jSlider2.setValue(100);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jSlider3.setMaximum(300);
        jSlider3.setValue(100);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        jLabel10.setText("field of view 1 max radius");

        jLabel11.setText("field of view 2 max radius");

        jLabel12.setText("field of view 3 max radius");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider1, org.jdesktop.beansbinding.ELProperty.create("${value}"), foV1rad, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        foV1rad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foV1radActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider2, org.jdesktop.beansbinding.ELProperty.create("${value}"), foV2rad, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSlider3, org.jdesktop.beansbinding.ELProperty.create("${value}"), foV3rad, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTurningSpeed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(jFieldOfView, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel8)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(boidsNoTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 246, Short.MAX_VALUE)
                                .add(PredatorDeathLabel))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .add(jLabel1))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 231, Short.MAX_VALUE)
                                        .add(PreyDeathLabel))
                                    .add(layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jLabel6)
                                            .add(jLabel7)))))
                            .add(layout.createSequentialGroup()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 126, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel10)
                            .add(jLabel11)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jSlider1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .add(jSlider3, 0, 0, Short.MAX_VALUE))
                            .add(jSlider2, 0, 0, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(foV1rad)
                            .add(foV2rad)
                            .add(foV3rad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .add(19, 19, 19)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButton1)
                            .add(jLabel6))
                        .add(7, 7, 7)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jButton2)
                                    .add(jLabel7))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(boidsNoTxtField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PredatorDeathLabel)))
                            .add(PreyDeathLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTurningSpeed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 95, Short.MAX_VALUE)
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(28, 28, 28)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)
                        .add(8, 8, 8)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFieldOfView, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(44, 44, 44))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(foV1rad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel10)
                                .add(jSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel11)
                                .add(18, 18, 18)
                                .add(jLabel12))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(foV2rad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jSlider2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(foV3rad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jSlider3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(370, Short.MAX_VALUE))))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTurningSpeedMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTurningSpeedMouseWheelMoved

        int notches = evt.getWheelRotation();
        
        if (notches < 0) {
            
            if (turningSpeed<100) {turningSpeed++;}
            
        } else {
            
            if (turningSpeed>0) {turningSpeed--;}
            
        }
        
        jTurningSpeed.setText(Integer.toString(turningSpeed));
        
        
    }//GEN-LAST:event_jTurningSpeedMouseWheelMoved

    private void jTextField1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTextField1MouseWheelMoved

        int notches = evt.getWheelRotation();
        
        if (notches < 0) {
            
            if (displaySpeed< 300) {displaySpeed++;}
            
        } else {
            
            if (displaySpeed>0) {displaySpeed--;}
            
        }
        
        jTextField1.setText(Integer.toString(displaySpeed));
        
        
    }//GEN-LAST:event_jTextField1MouseWheelMoved

    private void jFieldOfViewMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jFieldOfViewMouseWheelMoved

        int notches = evt.getWheelRotation();
        
        if (notches < 0) {
            
            if (showFieldOfView < 6) {showFieldOfView++;}
            
        } else {
            
            if (showFieldOfView>0) {showFieldOfView--;}
            
        }
        
        jFieldOfView.setText(Integer.toString(showFieldOfView));
        
    }//GEN-LAST:event_jFieldOfViewMouseWheelMoved

    private void jFieldOfViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldOfViewActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jFieldOfViewActionPerformed
    
    /** Method for allowing the user to change the number of boids before starting
     * Using the mouse wheel.  Minimum and maximum limit set here too.
     * Number = number of boids of each type, so 20 will lead to 40 in total
     */
    private void boidsNoTxtFieldMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_boidsNoTxtFieldMouseWheelMoved
        
        int notches = evt.getWheelRotation();
        
        if (notches < 0) {
            
//            if (boidsNumber < 50) {boidsNumber++;}
            boidsNumber++;
            
        } else {
            
            if (boidsNumber>0) {boidsNumber--;}
            
        }
        
        boidsNoTxtField.setText(Integer.toString(boidsNumber));
        
    }//GEN-LAST:event_boidsNoTxtFieldMouseWheelMoved
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //BoidsCage boidsCage = new BoidsCage(cageXY, boidsNumber);
        BoidsCage boidsCage = new BoidsCage(this);
        
        Thread boidsThread = new Thread(boidsCage);
        
        boidsThread.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void foV1radActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foV1radActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foV1radActionPerformed

    private void jSlider1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSlider1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1AncestorRemoved

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged

       Object source = evt.getSource();
       
       javax.swing.JSlider thisSlider = (javax.swing.JSlider) source;
       
       FIELDOFVIEWMAXRADIUS[0] = thisSlider.getValue();
        
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        
       Object source = evt.getSource();
       
       javax.swing.JSlider thisSlider = (javax.swing.JSlider) source;
       
       FIELDOFVIEWMAXRADIUS[1] = thisSlider.getValue();
       
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
       
       Object source = evt.getSource();
       
       javax.swing.JSlider thisSlider = (javax.swing.JSlider) source;
       
       FIELDOFVIEWMAXRADIUS[2] = thisSlider.getValue();
        
    }//GEN-LAST:event_jSlider3StateChanged

    
        
    
    
    //so's the birdcage can know how many birds it needs
    public int getBoidNumber() {
        
        return boidsNumber;
        
    }
    
    
    
    public void setPreyDeathNumber() {
        
        preyDeaths++;
        PreyDeathLabel.setText(Integer.toString(preyDeaths));
        
    }
    
    
    
    public void setPredatorDeathNumber() {
        
        predatorDeaths++;
        PredatorDeathLabel.setText(Integer.toString(predatorDeaths));
        
    }
    
    
    
    
    //for testing things and displaying them...
    
    public void setANumber (int x) {
        
        jFieldOfView.setText(String.valueOf(x));
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoidsStartUp().setVisible(true);
            }
        });
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PredatorDeathLabel;
    private javax.swing.JLabel PreyDeathLabel;
    private javax.swing.JTextField boidsNoTxtField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField foV1rad;
    private javax.swing.JTextField foV2rad;
    private javax.swing.JTextField foV3rad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jFieldOfView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTurningSpeed;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
    
    public static int[] CAGE_XY;
    public int showFieldOfView = 0;
    public int preyDeaths = 0;
    public int predatorDeaths = 0;
    public int displaySpeed = 0;
    public int boidsNumber = 75;
    public int turningSpeed = 3;
    public static int[] FIELDOFVIEWMAXRADIUS = {20,40,60};
//    public static int[] FIELDOFVIEWMAXRADIUS = {100,100,100};
//    public static int[] FIELDOFVIEWMAXRADIUS = {50,50,50};
}
